# Generated by Django 6.0.4 on 2026-05-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_ingredient_menuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
